<script setup lang="ts">
import { computed } from 'vue';
import { date, week, preferences, savedCourses } from '../scripts/calendarStore';
import { calendarWeekDays, frenchDate } from '../../shared/calendar';
const props = defineProps<{ daily?: boolean; list?: boolean }>();
const days = computed(() => props.daily ? [date.value] : calendarWeekDays(week.value, savedCourses.value));
const slots = [[{ start: 9, hours: 1.5 }, { start: 11, hours: 1 }, { start: 14, hours: 3 }], [{ start: 8, hours: 2 }, { start: 10.5, hours: 1.5 }, { start: 15, hours: 2 }], [{ start: 9, hours: 1 }, { start: 10.5, hours: 1.5 }, { start: 13, hours: 3 }]];
</script>
<template><div class="calendar-skeleton planning-skeleton" :class="{ 'daily-skeleton': daily, 'list-skeleton': list, 'full-skeleton': preferences.density === 'full' }" aria-busy="true"><p class="sr-only" role="status">Chargement du planning…</p>
<div v-if="list" class="list-calendar skeleton-list" :class="{ 'daily-list': daily }" :style="{ '--list-days': days.length }" aria-hidden="true"><section v-for="(day, index) in days" :key="day" class="list-day"><header v-if="!daily" class="list-day-heading"><h2>{{ frenchDate(day, { weekday: 'long' }) }}</h2><p>{{ frenchDate(day, { day: 'numeric', month: 'short' }) }}</p></header><template v-for="(slot, item) in slots[index % slots.length]" :key="item"><div v-if="!daily || item > 0" class="skeleton-pause" :style="{ height: (daily ? 48 : item === 0 ? (slot.start - 8) * 69 : 48) + 'px' }"><span></span></div><div class="skeleton-course skeleton-event list-course" :style="{ height: (daily ? preferences.density === 'full' ? 112 : 86 : Math.max(preferences.density === 'full' ? 124 : 104, slot.hours * 69)) + 'px' }"><span class="skeleton-event-meta"></span><span class="skeleton-event-time"></span><strong class="skeleton-event-title"></strong><span class="skeleton-event-room"></span><span v-if="preferences.density === 'full'" class="skeleton-event-room"></span><span v-if="preferences.density === 'full'" class="skeleton-event-room"></span></div></template></section></div>
<div v-else class="skeleton-grid calendar-scroll" aria-hidden="true"><div class="skeleton-grid-head" :style="{ '--skeleton-days': days.length }"><span class="skeleton-axis-label">h</span><div v-for="day in days" :key="day" class="skeleton-date"><span>{{ frenchDate(day, { weekday: 'short' }) }}</span><strong>{{ frenchDate(day, { day: 'numeric' }) }}</strong></div></div><div class="skeleton-grid-body" :style="{ '--skeleton-days': days.length }"><div class="skeleton-hours"><span v-for="hour in 12" :key="hour" :style="{ top: 'calc(' + (hour - 1) + ' * var(--skeleton-hour-height))' }">{{ String(hour + 7).padStart(2, '0') }}</span></div><section v-for="(day, index) in days" :key="day" class="skeleton-grid-column"><div v-for="(slot, item) in slots[index % slots.length]" :key="item" class="skeleton-course skeleton-event" :style="{ top: 'calc(' + (slot.start - 8) + ' * var(--skeleton-hour-height))', height: 'calc(' + slot.hours + ' * var(--skeleton-hour-height) - 4px)' }"><span class="skeleton-event-meta"></span><span class="skeleton-event-time"></span><strong class="skeleton-event-title"></strong><span class="skeleton-event-room"></span><span v-if="preferences.density === 'full'" class="skeleton-event-room"></span></div></section></div></div>
</div></template>
